### ISSUE TITLE
Ability to set SNR (related to pathloss)

### ISSUE THREAD

**Issue by artiommocrenco** [GUVWAF/Meshtasticator#13]
Hello,

This is more like a question

I haven't found a documented way to set link SNR, meaning how well a node is able to hear another node.

This would help so much especially if I use data from neighbor info, to simulate the network.

Are significant changes needed on my side in order to set SNR somehow?

**Comment by GUVWAF** [comment]
Hi, 

SNR is calculated based on the RSSI and a noise level, which you can configure in [config.py](https://github.com/GUVWAF/Meshtasticator/blob/f67084f30791700050765c49fbdd06ec3b048881/lib/config.py#L50), but it is assumed to be the same everywhere. [RSSI](https://github.com/GUVWAF/Meshtasticator/blob/f67084f30791700050765c49fbdd06ec3b048881/lib/packet.py#L40) is calculated based on the [pathloss model](https://github.com/GUVWAF/Meshtasticator/blob/master/DISCRETE_EVENT_SIM.md#model), the distance between each node, their [transmit power](https://github.com/GUVWAF/Meshtasticator/blob/f67084f30791700050765c49fbdd06ec3b048881/lib/config.py#L38) (which is the same for each node and based on the region you set), and antenna gain. You can specify the antenna gain for each node when you place them.

Hope this helps.

**Comment by artiommocrenco** [comment]
> Hi, 
> 
> 
> 
> SNR is calculated based on the RSSI and a noise level, which you can configure in [config.py](https://github.com/GUVWAF/Meshtasticator/blob/f67084f30791700050765c49fbdd06ec3b048881/lib/config.py#L50), but it is assumed to be the same everywhere. [RSSI](https://github.com/GUVWAF/Meshtasticator/blob/f67084f30791700050765c49fbdd06ec3b048881/lib/packet.py#L40) is calculated based on the [pathloss model](https://github.com/GUVWAF/Meshtasticator/blob/master/DISCRETE_EVENT_SIM.md#model), the distance between each node, their [transmit power](https://github.com/GUVWAF/Meshtasticator/blob/f67084f30791700050765c49fbdd06ec3b048881/lib/config.py#L38) (which is the same for each node and based on the region you set), and antenna gain. You can specify the antenna gain for each node when you place them.
> 
> 
> 
> Hope this helps.

Ah thanks so much, the reason why I'm asking is because in firmware I found that delay before flooding a message is dependant on SNR, and there also is some randomness

**Comment by GUVWAF** [comment]
Yes, indeed. The simulator calculates this as well: https://github.com/GUVWAF/Meshtasticator/blob/f67084f30791700050765c49fbdd06ec3b048881/lib/mac.py#L19-L36

**Comment by artiommocrenco** [comment]
Thank you so much!

**Comment by artiommocrenco** [comment]
This is very helpful to simulate the mesh we have here in Moldova, Chisinau

**Comment by GUVWAF** [comment]
Great to hear! I'll close this issue now. Feel free to open another if you have further questions.
