### ISSUE TITLE
Specify that Native Linux Requires GNOME Desktop Environment

### ISSUE THREAD

**Issue by ajmcquilkin** [GUVWAF/Meshtasticator#5]
Currently, the "Interactive Simulator" documentation page does not specify the application's depenency on the [GNOME desktop environment](https://www.gnome.org/). There is a [dependency](https://github.com/GUVWAF/Meshtasticator/blob/1ff418adfa08894f1f07fd0d40e1e9cf2ba86646/lib/interactive.py#L307) within the codebase on `gnome-terminal`, which is not supported on all Linux desktop environments. While `xterm` would work for all X11 DEs, this would also not support wayland DEs. I'm not sure of the best way to handle this since to my knowledge there isn't a generic command to start a terminal that is widely supported, although at least this is worth pointing out in the "Interactive Simulator" docs as a note.

**Comment by GUVWAF** [comment]
Thanks for pointing that out. I was able to make it work with `xterm` by replacing lines 307-308 with: 
```
newTerminal = "xterm -title 'Node "+str(n.nodeid)+"' -e "
cmdString = newTerminal+pathToProgram+"program -e -d "+os.path.expanduser('~')+"/.portduino/node"+str(n.nodeid)+" -h "+str(n.hwId)+" -p "+str(n.TCPPort)+ " &"
```

I will try to come up with a more generic way of doing this.

**Comment by ajmcquilkin** [comment]
Good to know, thanks! I'm wondering if it would be worth picking a default terminal that *most* Linux DEs would have (maybe `xterm`) then allowing for a terminal override in the form of `--t "gnome-terminal"` or something like that. I'm imagining determining which DE a given user is on would be too much trouble to be worth the time

**Comment by GUVWAF** [comment]
While maybe not the most elegant way, I now check with `shutil` (which is installed with Python by default) whether `gnome-terminal` is available. If not, it checks for `xterm` and if that is not available, it simply reports that one of them is required.

Thanks again.
