### ISSUE TITLE
No documentation for "tk" python failure

### ISSUE THREAD

**Issue by ajmcquilkin** [GUVWAF/Meshtasticator#7]
When installing this repo on a new server, the sim failed due to `tk` not being installed on the machine. I couldn't find any docs on this, so it might be worth placing a note about needing this at the system level to run the application, if not giving some demo commands. For example, `sudo pacman -S tk` fixes the problem on Arch Linux.

**Comment by GUVWAF** [comment]
Coincidentally, somebody else reported this as well and I just added an ImportError catch in [this commit](https://github.com/GUVWAF/Meshtasticator/commit/6b16e46cd40b916fed27e7f426b05a2cc9eac28a). Problem is indeed that it cannot be installed using pip, so I recommend people to install tk using their package manager. On Debian systems, it's `apt-get install python3-tk`, for example.

Thanks for reporting though.

**Comment by ajmcquilkin** [comment]
Yeah for sure! I had seen that commit, I'm wondering if there's a way to make it very clear to users that have that issue that the issue is a missing package instead of another build issue. I had a bit of experience with tk before which was why I knew to install it

**Comment by GUVWAF** [comment]
Ah, I see. What would you propose to make it more clear, maybe by giving some example commands?

**Comment by ajmcquilkin** [comment]
I was thinking even something as simple as a note in the installing section, maybe in the `Usage` subheaders in the discrete and interactive sim docs. I was imagining that the docs could say something to the effect of "If you run into a build issue that looks like [describe the issue], make sure you have tkinter installed on your computer."

**Comment by GUVWAF** [comment]
Now they will be faced with "Tkinter is needed. Install python3-tk with your package manager." when it failed to import, no other error message, as I catch it. Would that suffice?
I think it is installed by default from Python 3.7 on, so I would rather not make the install instructions longer, if possible.

**Comment by ajmcquilkin** [comment]
Oh yeah that sounds great! Honestly just anything that will let newer users know what's going wrong when tkinter isn't on the system, totally get not wanting to extend the docs

**Comment by GUVWAF** [comment]
Okay, thanks!
